GET  http://localhost:3000

### Get the list of all songs
GET  http://localhost:3000/songs

### Get the song based on id
GET  http://localhost:3000/songs/abvc

### Create a new song
POST   http://localhost:3000/songs
Content-Type: application/json

{
    "title":"Tum hi ho",
    "artists":["arijit"],
    "releaseDate":"2024-03-10",
    "duration":"03:10"
}

### Update a existing song based on id
PUT   http://localhost:3000/songs/1

### Delete a existing song based on id
DELETE   http://localhost:3000/songs/1

### create new playlist
POST http://localhost:3001/playlists
Content-Type: application/json

{
    "name":"feel good now",
    "songs":[
        6
    ],
    "user":2
}