GET  http://localhost:3000

### Get the list of all songs
GET  http://localhost:3000/songs

### Get the song based on id
GET  http://localhost:3000/songs/abvc

### Create a new song
POST   http://localhost:3001/songs
Content-Type: application/json
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Rpbmd0QGdtYWlsLmNvbSIsInVzZXJJZCI6OSwiYXJ0aXN0SWQiOjQsImlhdCI6MTc0MTE3MDMwMSwiZXhwIjoxNzQxMjU2NzAxfQ.MY859mKO6qvV06UqImOccOMdEMBk5KUNHzy6geLgnNg

{
    "title": "Blue eyes",
    "artists": [
        4
    ],
    "releasedDate":"2024-05-04",
    "duration": "03:10",
    "lyrics":"You better not ever go to cell block one To any bitch that talk to him and they in love Just make sure you hide your lil' sister from him They tell me Chubbs the only one that get your hand-me-downs And Party at the party playin' with his nose now And Baka got a weird case"
}

### Update a existing song based on id
PUT   http://localhost:3000/songs/1

### Delete a existing song based on id
DELETE   http://localhost:3000/songs/1

### create new playlist
POST http://localhost:3000/playlists
Content-Type: application/json

{
    "name":"feel good now",
    "songs":[
        6
    ],
    "user":2
}

### register new user
POST http://localhost:3001/auth
Content-Type: application/json

{
    "firstName":"divesh",
    "lastName":"rajpoot",
    "email":"testing@gmail.com",
    "password":"1234567890"
}

### login the user
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email":"test1@gmail.com",
    "password":"1234567890"
}

# ACCESS TOKEN eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsImZpcnN0bmFtZSI6ImRpdmVzaCIsImxhc3RuYW1lIjoicmFqcG9vdCIsInVzZXJJZCI6OCwiaWF0IjoxNzQxMTU3OTc5LCJleHAiOjE3NDEyNDQzNzl9.ZBJUU7XLI2CAk-Y9lmVePffjoEHa9Km7isZHlqEzHeg

###  profile
GET http://localhost:3001/profile
Content-Type: application/json
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Rpbmd0QGdtYWlsLmNvbSIsInVzZXJJZCI6OSwiYXJ0aXN0SWQiOjQsImlhdCI6MTc0MTE3MDMwMSwiZXhwIjoxNzQxMjU2NzAxfQ.MY859mKO6qvV06UqImOccOMdEMBk5KUNHzy6geLgnNg


### login the artist
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email":"testingt@gmail.com",
    "password":"1234567890"
}

### enable 2fa 
GET http://localhost:3001/auth/enable-2fa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Rpbmd0QGdtYWlsLmNvbSIsInVzZXJJZCI6OSwiYXJ0aXN0SWQiOjQsImlhdCI6MTc0MTE3MDMwMSwiZXhwIjoxNzQxMjU2NzAxfQ.MY859mKO6qvV06UqImOccOMdEMBk5KUNHzy6geLgnNg

### verify 2fa otp
POST http://localhost:3001/auth/validate-2FA
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Rpbmd0QGdtYWlsLmNvbSIsInVzZXJJZCI6OSwiYXJ0aXN0SWQiOjQsImlhdCI6MTc0MTE3MDMwMSwiZXhwIjoxNzQxMjU2NzAxfQ.MY859mKO6qvV06UqImOccOMdEMBk5KUNHzy6geLgnNg

{
    "token":"203627"

}

### disble 2fa 
GET http://localhost:3001/auth/disable-2fa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Rpbmd0QGdtYWlsLmNvbSIsInVzZXJJZCI6OSwiYXJ0aXN0SWQiOjQsImlhdCI6MTc0MTE3MDMwMSwiZXhwIjoxNzQxMjU2NzAxfQ.MY859mKO6qvV06UqImOccOMdEMBk5KUNHzy6geLgnNg


### get profile using api key
GET http://localhost:3001/profile
Content-Type: application/json
Authorization: Bearer 39c1e4de-d34a-4d3b-a349-e50d2bc8dbd6