GET  http://localhost:3000

### Get the list of all songs
GET  http://localhost:3000/songs

### Get the song based on id
GET  http://localhost:3000/songs/abvc

### Create a new song
POST   http://localhost:3000/songs
Content-Type: application/json

{
    "title": "Not Like Us 3",
    "artists": [
        "Kendrick Lamar"
    ],
    "releasedDate":"2024-05-04",
    "duration": "03:10",
    "lyrics":"You better not ever go to cell block one To any bitch that talk to him and they in love Just make sure you hide your lil' sister from him They tell me Chubbs the only one that get your hand-me-downs And Party at the party playin' with his nose now And Baka got a weird case"
}

### Update a existing song based on id
PUT   http://localhost:3000/songs/1

### Delete a existing song based on id
DELETE   http://localhost:3000/songs/1

### create new playlist
POST http://localhost:3000/playlists
Content-Type: application/json

{
    "name":"feel good now",
    "songs":[
        6
    ],
    "user":2
}